package Client.View;

import Client.Controller.ChatController;
import Client.Controller.ChatObserved;
import Client.Controller.ChatObserver;
import Client.Controller.Controller;

import javax.swing.*;
import javax.swing.text.DefaultCaret;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class Chat extends javax.swing.JPanel implements ChatObserver {

    private ChatObserved controller;
    private Controller app;
            
    
    public Chat(ChatObserved controller, Controller app) {
        initComponents();
        this.controller = controller;
        this.controller.addObserver(this);
        this.app = app;
        controller.nameUser();
        controller.setStatus();

        DefaultCaret caret = (DefaultCaret) this.taChat.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        btnSend = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        imgStatus = new javax.swing.JLabel();
        lbContactName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taMessage = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(676, 658));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taChat.setEditable(false);
        taChat.setColumns(20);
        taChat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taChat.setRows(22);
        taChat.setBorder(null);
        taChat.setFocusable(false);
        taChat.setOpaque(false);
        jScrollPane2.setViewportView(taChat);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 79, 649, 502));

        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/send-button.png"))); // NOI18N
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 593, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contact.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, -1, -1));

        lbStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbStatus.setText("Online");
        add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 41, -1, 12));

        imgStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/online.png"))); // NOI18N
        add(imgStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 41, -1, -1));

        lbContactName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbContactName.setForeground(new java.awt.Color(102, 102, 102));
        lbContactName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbContactName.setText("Nome");
        add(lbContactName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 16, 592, 19));

        taMessage.setColumns(20);
        taMessage.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taMessage.setRows(2);
        taMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taMessage.setOpaque(false);
        taMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taMessageKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(taMessage);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 593, 595, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked
        if (!taMessage.getText().isEmpty()) {
            this.controller.onSendMessage(this.taMessage.getText());
        }
    }//GEN-LAST:event_btnSendMouseClicked

    private void taMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taMessageKeyPressed
        if (!taMessage.getText().isEmpty()) {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                this.controller.onSendMessage(this.taMessage.getText());
            }
        }
    }//GEN-LAST:event_taMessageKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSend;
    private javax.swing.JLabel imgStatus;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbContactName;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextArea taMessage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateName(String name) {
        this.lbContactName.setText(name);
    }

    @Override
    public void setStatus(String status) {

        this.lbStatus.setText(status);
        this.imgStatus.setIcon(new ImageIcon(getClass().getResource("/img/"+status+".png")));
    }

    @Override
    public void updateScreen(String message) {
        this.taChat.append(message+"\n");
        this.taMessage.setText(null);
    }

    public ChatObserved getController() {
        return controller;
    }

    public JLabel getLbContactName() {
        return lbContactName;
    }

    public JTextArea getTaChat() {
        return taChat;
    }

    public JTextArea getTaMessage() {
        return taMessage;
    }
    
    
}
