package Client.View;

import Client.Controller.ChatObserved;
import Client.Controller.ChatObserver;
import Client.Controller.Controller;
import javax.swing.JLabel;
import javax.swing.JTextArea;

public class Chat extends javax.swing.JPanel implements ChatObserver {

    private ChatObserved controller;
    private Controller app;
            
    
    public Chat(ChatObserved controller, Controller app) {
        this.controller = controller;
        this.controller.addObserver(this);
        this.app = app;
        controller.nameUser();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        btnSend = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        imgStatus = new javax.swing.JLabel();
        lbContactName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taMessage = new javax.swing.JTextArea();

        taChat.setEditable(false);
        taChat.setColumns(20);
        taChat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taChat.setRows(22);
        taChat.setBorder(null);
        taChat.setFocusable(false);
        taChat.setOpaque(false);
        jScrollPane2.setViewportView(taChat);

        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/send-button.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contact.png"))); // NOI18N

        lbStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbStatus.setText("Online");

        imgStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/online.png"))); // NOI18N

        lbContactName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbContactName.setForeground(new java.awt.Color(102, 102, 102));
        lbContactName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbContactName.setText("Nome");

        taMessage.setColumns(20);
        taMessage.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taMessage.setRows(2);
        taMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taMessage.setOpaque(false);
        jScrollPane3.setViewportView(taMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imgStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbContactName, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbContactName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imgStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSend)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSend;
    private javax.swing.JLabel imgStatus;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbContactName;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextArea taMessage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateName(String name) {
        this.lbContactName.setText(name);
    }

    @Override
    public void updateScreen(String message) {
        this.taChat.append(message+"\n");
        this.taMessage.setText("");
    }

    public ChatObserved getController() {
        return controller;
    }

    public JLabel getLbContactName() {
        return lbContactName;
    }

    public JTextArea getTaChat() {
        return taChat;
    }

    public JTextArea getTaMessage() {
        return taMessage;
    }
    
    
}
